name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94a206b26ad6e841d4341e59da37666119e498f611298721d00960b7dec29183"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
