name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fd1d35ee8514f2aa906b6732acbce82f3630534685cfd22dcb1d1bd3cd3d38d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
