name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6100488a13579bfd58dc0b6e2732658719d29db710acd9db8eb3bb27e49d2a8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
