name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.7+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcb7aae011dac4adaea056ff15edf335a62565bfec299f8c3b08d053471843ef"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
