name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a26df01622fc9a4bd3f3f138089fadfa965c8ca3c50285d14be5d07682ee0989"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
