name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.3+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0eccdce17b86c0e4377dd8efb7853b51f1ba306dba9366f7f687d7f929e35615"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
