name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.2+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a71a8ca0238e3fd984408bb65c2e163c08c0bd5f23197fab933e004b4adf0b9e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
