name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.8+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0fcd403cf2594091f721fa7fdc461a53951944f12cc2ab8300b77c590f2cf43"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
