name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.6+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bcf682e29354774b75897f22fc0d1a16b85009e3886f48f09621cce5217904c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
