name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.7+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62a130d70b1faacc07826e9014abf7561d13acae56dfcecf5c9b3b65e5322be0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
