name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a34d03fd589428b8f4a6b015f8f9de7e1079667a757cc11a19ea148b68fd18d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
