name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc1bc9fdf0526f1d50a2a64a5a514aa56f026de2eeaa7de723622f2c00376d60"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
