name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.4+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbfae6b22ec5ceaef00f26c7b0bee084fe368219d36bdc59ed8d967183ec85f0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
