name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33c32cdb6d97b168f31ede3ef2aff020eb35d620e532cf6a0aebf399b4690c97"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
