name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10db6b57e13b4915659c6012b00e724688ee74dcb2de80172bdd16da1b2e089d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
