name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.5+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87566cc3693a3da77f1c423ecc0818017ce208e863d377baf04540a799b18b16"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
