name = "Devin's Overhaul"
author = "intergrav"
version = "1.0.5+mc1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e7474da29e74f45bfab8e9c2549049bdc4ef71947a943889763218fefa1851d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
